---
- name: Setting conditional decisions to install apps on the servers
  hosts: all
  become: yes
  tasks:
  - name: Install NTP on centos
    yum:
      name: ntp
      state: present
    when: ansible_distribution == "CentOS"

  - name: install NTP on Ubuntu
    apt:
      name: ntp
      state: present
    when: ansible_distribution == "Ubuntu"