---
- name: Setup WebServer
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache httpd 
      yum:
        name: httpd
        state: present
    
    - name: Start & Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes
