---
- name: Setup WebServer
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache httpd 
      yum:
        name: httpd
        state: present
    
    - name: Copy file with owner and permissions
      copy:
        src: webfiles/index.html
        dest: /var/www/html/index.html