- name: setup DB server
  hosts: dbservers
  become: yes
  tasks:
    - name: install mariadb
      yum: 
        name: mariadb-server
        state: present

    - name: Install MySQL-python
      yum:
        name: MySQL-python
        state: present

    - name: start & enable dbservers
      service: 
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present