---
- name: 
  hosts: all
  become: yes
  tasks:
    - name: Banner file /etc/motd
      copy: 
        content: "This {{ansible_distribution}} is managed by Ansible. \n"
        dest: /etc/motd

    - name: Deploy NTP conf file for RedHat
      template:
        src: ../templates/ntp_redhat.conf.j2
        dest: /etc/ntp.conf
      when: ansible_os_family == "RedHat"
      notify: 
        - Restart NTP on RedHat

    - name: Dir for dev data
      file:
        path: /opt/devdata
        state: directory
        mode: 0775
        
  handlers:
    - name: Restart NTP on RedHat
      service: 
        name: ntpd
        state: restarted
        enabled: yes
      when: ansible_os_family == "RedHat"

    