---
- name: Create user on all hosts
  hosts: all
  become: yes
  vars: 
    USRNM: playUser
    COMM: variable from playbook
  tasks: 
    - name: create user
      user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: usrout

    - debug: 
        var: usrout.name

    - debug: 
        var: usrout.comment
