- name: setup DB server
  hosts: dbservers
  become: yes
  vars:
    dbname: electric
    dbuser: current
    dbpass: tesla

  tasks:
    - debug: 
        msg: "The name of the db is {{dbname}}"
    - debug:
        var: dbuser
    - name: install mariadb
      yum: 
        name: mariadb-server
        state: present

    - name: Install MySQL-python
      yum:
        name: MySQL-python
        state: present

    - name: start & enable dbservers
      service: 
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Create database user using hashed password with all database privileges
      no_log: true
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
      register: dbout

    - name: print out the output of dbuser
      debug:
        var: dbout